config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cartapp/", include("cartapp.urls", namespace="cartapp")),
    path("orderapp/", include("orderapp.urls", namespace="orderapp")),
    path("paymentapp/", include("paymentapp.urls", namespace="paymentapp")),
    path("", include("shopapp.urls", namespace="shopapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paymentapp/urls.py
from django.urls import path

from paymentapp import views, webhooks

app_name = "paymentapp"

urlpatterns = [
    path("process/", views.payment_process, name="process"),
    path("completed/", views.payment_completed, name="completed"),
    path("canceled/", views.payment_canceled, name="canceled"),
    path("webhook/", webhooks.stripe_webkook, name="stripe-webhook"),
]

paymentapp/models.py
from django.db import models

# Create your models here.

paymentapp/views.py
from decimal import Decimal

import stripe
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render, reverse

from orderapp import models as orderapp_models

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(orderapp_models.Order, id=order_id)
    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("paymentapp:completed"))
        cancel_url = request.build_absolute_uri(reverse("paymentapp:canceled"))

        # данные сеанса оформления платежа
        session_data = {
            "mode": "payment",
            "client_reference_id": order.id,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "line_items": [],
        }

        for item in order.items.all():
            session_data["line_items"].append(
                {
                    "price_data": {
                        "unit_amount": int(item.price * Decimal("100")),
                        "currency": "usd",
                        "product_data": {
                            "name": item.product.name,
                        },
                    },
                    "quantity": item.quantity,
                }
            )

        # Создать сеанс оформления платежа Stripe
        session = stripe.checkout.Session.create(**session_data)

        # Перенаправить к платежной форме Stripe
        return redirect(session.url, code=303)
    else:
        return render(request, "paymentapp/process.html", locals())


def payment_completed(request):
    return render(request, "paymentapp/completed.html")


def payment_canceled(request):
    return render(request, "paymentapp/canceled.html")

paymentapp/templates/paymentapp/canceled.html
{% extends 'shopapp/base.html' %}

{% block title %}Payment canceled{% endblock title %}

{% block content %}
	<h1>Your payment has not been processed</h1>
    <p>There was a problem processing your payment.</p>
{% endblock %}

paymentapp/templates/paymentapp/completed.html
{% extends 'shopapp/base.html' %}

{% block title %}Payment successsul{% endblock title %}

{% block content %}
	<h1>Your payment was successful</h1>
    <p>Your payment has been processed successully.</p>
{% endblock %}

paymentapp/templates/paymentapp/process.html
{% extends 'shopapp/base.html' %}
{% load static %}

{% block title %}Pay your order{% endblock title %}

{% block content %}
    <h1>Order summary</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle '1' '2' %}">
                <td>
                    <img src="
                        {% if item.product.image %}{{ item.product.image.url }}{% else %}{% static 'img/no/image.png' %}{% endif %}"
                         alt="img">
                </td>
                <td>{{ item.product.name }}</td>
                <td class="num">${{ item.price }}</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">{{ item.get_cost }}</td>
            </tr>
        {% endfor %}
        <tr class="total">
            <td colspan="4">Total</td>
            <td class="num">${{ order.get_total_cost }}</td>
        </tr>
        </tbody>
    </table>
    <form action="{% url 'paymentapp:process' %}" method="post">
        <input type="submit" value="Pay now">
        {% csrf_token %}
    </form>
{% endblock content %}