cartapp/urls.py
from django.urls import path

from cartapp import views

app_name = "cartapp"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cartapp/", include("cartapp.urls", namespace="cartapp")),
    path("orderapp/", include("orderapp.urls", namespace="orderapp")),
    path("paymentapp/", include("paymentapp.urls", namespace="paymentapp")),
    path("", include("shopapp.urls", namespace="shopapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/urls.py
from django.urls import path

from shopapp import views

app_name = "shopapp"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

shopapp/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"]),
        ]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shopapp:product_list_by_category", args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["name"]),
            models.Index(fields=["-created"]),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shopapp:product_detail", args=[self.id, self.slug])

shopapp/views.py
from django.shortcuts import get_object_or_404, render

from cartapp.forms import CartAddProductForm
from shopapp import models as shopapp_models


def product_list(request, category_slug=None):
    category = None
    categories = shopapp_models.Category.objects.all()
    products = shopapp_models.Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(shopapp_models.Category, slug=category_slug)
        products = products.filter(category=category)

    return render(
        request, "shopapp/product/list.html", {"category": category, "categories": categories, "products": products}
    )


def product_detail(request, id, slug):
    product = get_object_or_404(shopapp_models.Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, "shopapp/product/detail.html", {"product": product, "cart_product_form": cart_product_form})

shopapp/templates/shopapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My shop{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                	Your cart:
                    <a href="{% url 'cartapp:cart_detail' %}">
                        {{ total_items }} item{{ total_items|pluralize }},
                        ${{ cart.get_total_price }}
                    </a>
                {% elif not order %}
                    Your cart empty
                {% endif %} 
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>